import re

def uid_to_acro(uid):
    
    result = re.sub(r'[a-zA-Z]+', lambda m: uid_to_acro_map.get(m[0]) or m[0].upper(), uid)
    result = re.sub(r'(\d+)-(\d+)', r'\1–\2', result)
    result = re.sub('-', ' ', result)
    result = re.sub(r'([a-zA-Z])(\d)', r'\1 \2', result)
    return result

uid_to_acro_map = {
  "an": "AN",
  "ap": "Ap",
  "arv": "Arv",
  "avs": "Avs",
  "bv": "Bv",
  "cnd": "Cnd",
  "cp": "Cp",
  "cps": "Cps",
  "da": "DA",
  "kag": "KA",
  "dhp": "Dhp",
  "gdhp": "G-Dhp",
  "g2dhp": "G-2-Dhp",
  "g3dhp": "G-3-Dhp",
  "pdhp": "P-Dhp",
  "divy": "Divy",
  "dk": "Dk",
  "dn": "DN",
  "d": "D",
  "q": "Q",
  "dt": "Dt",
  "dr": "Dr",
  "ds": "Ds",
  "ea": "EA",
  "ea-2": "EA2 [T 150A]",
  "gf": "Gandh",
  "iti": "Iti",
  "isi": "Isibhās",
  "ja": "Ja",
  "jp": "Jp",
  "kam": "Kam",
  "kf": "Khot",
  "kg": "Kg",
  "kn": "KN",
  "kp": "Kp",
  "kv": "Kv",
  "khv": "Khv",
  "lal": "Lal",
  "ma": "MA",
  "mbh": "Mbh",
  "mc": "Mc",
  "mpt": "Mpt",
  "mh": "Mh",
  "mil": "Mil",
  "mn": "MN",
  "mnd": "Mnd",
  "ms": "Ms",
  "mvu": "Mvu",
  "nd": "Nd",
  "ne": "Ne",
  "t1670a": "T 1670 A",
  "t1670b": "T 1670 B",
  "oa": "OA",
  "om": "OM",
  "pe": "Pe",
  "pk": "Pk",
  "pp": "Pp",
  "ps": "Ps",
  "patthana": "Patthana",
  "pf": "PF",
  "pu": "Pu",
  "praj": "Praj",
  "pv": "Pv",
  "sa": "SA",
  "sa-2": "SA-2",
  "sa-3": "SA-3",
  "sab": "Sab",
  "sag": "Sag",
  "sb": "Sb",
  "sbh": "Sbh",
  "sf": "SF",
  "sg": "Sg",
  "sht": "SHT",
  "sn": "SN",
  "snp": "Snp",
  "spp": "Spp",
  "suy": "Sūy",
  "t": "T",
  "other-t": "Other T",
  "tha-ap": "Tha Ap",
  "thag": "Thag",
  "thi-ap": "Thi Ap",
  "thig": "Thig",
  "tib": "Tib",
  "ud": "Ud",
  "uf": "Uigh",
  "up": "Up",
  "upp": "Upp",
  "utt": "Utt",
  "utg": "Utg",
  "uv": "Uv",
  "uvs": "UvS",
  "ve": "VE",
  "vk": "Vk",
  "vns": "Vns",
  "vs": "VS",
  "vv": "Vv",
  "ya": "Ya",
  "ybs": "Ybs",
  "nidana": "Nidana",
  "pli": "Pli",
  "zh": "Zh",
  "lzh": "Lzh",
  "san": "San",
  "pgd": "Pgd",
  "pra": "Pra",
  "uig": "Uig",
  "xct": "Xct",
  "my": "My",
  "de": "De",
  "en": "En",
  "es": "Es",
  "fr": "Fr",
  "ko": "Ko",
  "ru": "Ru",
  "vi": "Vi",
  "kho": "Kho",
  "abhidhamma": "Abhidhamma",
  "sutta": "Sutta",
  "vinaya": "Vinaya",
  "tv": "Tv",
  "vb": "Vb",
  "pm": "Pm",
  "pvr": "Pvr",
  "sarv": "Sarv",
  "mu": "Mu",
  "mi": "Mi",
  "mg": "Mg",
  "lo": "Lo",
  "dg": "Dg",
  "ka": "Ka",
  "hv": "Hv",
  "bf": "Bf",
  "qizil": "Qizil",
  "tf": "Tf",
  "finot": "Finot",
  "ba": "BA",
  "dh": "DH",
  "sc": "SC",
  "pj": "Pj",
  "ss": "Ss",
  "ay": "Ay",
  "np": "NP",
  "pc": "Pc",
  "pd": "Pd",
  "sk": "Sk",
  "as": "As",
  "du": "Du",
  "tl": "Tl",
  "asc": "Asc",
  "bu": "Bu",
  "bi": "Bi",
  "pn": "Pn",
  "conc": "Conc.",
  "gd": "Gd",
  "cases": "cases",
  "vagga": "Vagga",
  "kd": "Kd",
  "acip": "ACIP",
  "cbeta": "CBETA",
  "ddb": "DDB",
  "dy": "Dy",
  "f": "F",
  "g": "G",
  "gbm": "GBM",
  "gretil": "GRETIL",
  "hf": "Hf",
  "hsan": "Hsan",
  "ks": "KS",
  "ll": "ll",
  "p": "P",
  "vol": "Vol",
  "ed": "ed",
  "c-a": "C-A",
  "c1": "C1",
  "cha1": "C1",
  "c2": "C2",
  "c3": "C3",
  "cha2": "C2",
  "cha3": "C3",
  "mr": "Mr",
  "ka-ma": "Mr",
  "si": "Si",
  "km": "Km",
  "maku": " Maku",
  "pts-a": "PTS-A",
  "pts1": "PTS 1",
  "pa1": "PTS 1",
  "pts2": "PTS 2",
  "pa2": "PTS 2",
  "s-a": "S-A",
  "s1": "S 1",
  "s2": "S 2",
  "s3": "S 3",
  "sya1": "S 1",
  "sya2": "S 2",
  "sya3": "S 3",
  "sya1-3": "S 1-3",
  "bj": "Bj",
  "bj-a": " Bj A",
  "wp": "WP"
}
